# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blogkeeper.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blogkeeper.proto',
  package='blogkeeper',
  syntax='proto3',
  serialized_options=b'P\001\242\002\003BLG',
  serialized_pb=b'\n\x10\x62logkeeper.proto\x12\nblogkeeper\"\x14\n\x04\x42log\x12\x0c\n\x04name\x18\x01 \x01(\t\"R\n\x0b\x42logSummary\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x12number_of_articles\x18\x02 \x01(\x05\x12\x19\n\x11number_of_authors\x18\x03 \x01(\x05\":\n\x07\x41rticle\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t2\x7f\n\nBlogKeeper\x12\x36\n\x07GetInfo\x12\x10.blogkeeper.Blog\x1a\x17.blogkeeper.BlogSummary\"\x00\x12\x39\n\x0cListArticles\x12\x10.blogkeeper.Blog\x1a\x13.blogkeeper.Article\"\x00\x30\x01\x42\x08P\x01\xa2\x02\x03\x42LGb\x06proto3'
)




_BLOG = _descriptor.Descriptor(
  name='Blog',
  full_name='blogkeeper.Blog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='blogkeeper.Blog.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=52,
)


_BLOGSUMMARY = _descriptor.Descriptor(
  name='BlogSummary',
  full_name='blogkeeper.BlogSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='blogkeeper.BlogSummary.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_articles', full_name='blogkeeper.BlogSummary.number_of_articles', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_authors', full_name='blogkeeper.BlogSummary.number_of_authors', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=136,
)


_ARTICLE = _descriptor.Descriptor(
  name='Article',
  full_name='blogkeeper.Article',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='blogkeeper.Article.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='blogkeeper.Article.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='blogkeeper.Article.category', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['Blog'] = _BLOG
DESCRIPTOR.message_types_by_name['BlogSummary'] = _BLOGSUMMARY
DESCRIPTOR.message_types_by_name['Article'] = _ARTICLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blog = _reflection.GeneratedProtocolMessageType('Blog', (_message.Message,), {
  'DESCRIPTOR' : _BLOG,
  '__module__' : 'blogkeeper_pb2'
  # @@protoc_insertion_point(class_scope:blogkeeper.Blog)
  })
_sym_db.RegisterMessage(Blog)

BlogSummary = _reflection.GeneratedProtocolMessageType('BlogSummary', (_message.Message,), {
  'DESCRIPTOR' : _BLOGSUMMARY,
  '__module__' : 'blogkeeper_pb2'
  # @@protoc_insertion_point(class_scope:blogkeeper.BlogSummary)
  })
_sym_db.RegisterMessage(BlogSummary)

Article = _reflection.GeneratedProtocolMessageType('Article', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLE,
  '__module__' : 'blogkeeper_pb2'
  # @@protoc_insertion_point(class_scope:blogkeeper.Article)
  })
_sym_db.RegisterMessage(Article)


DESCRIPTOR._options = None

_BLOGKEEPER = _descriptor.ServiceDescriptor(
  name='BlogKeeper',
  full_name='blogkeeper.BlogKeeper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=198,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInfo',
    full_name='blogkeeper.BlogKeeper.GetInfo',
    index=0,
    containing_service=None,
    input_type=_BLOG,
    output_type=_BLOGSUMMARY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListArticles',
    full_name='blogkeeper.BlogKeeper.ListArticles',
    index=1,
    containing_service=None,
    input_type=_BLOG,
    output_type=_ARTICLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOGKEEPER)

DESCRIPTOR.services_by_name['BlogKeeper'] = _BLOGKEEPER

# @@protoc_insertion_point(module_scope)
