# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import blogkeeper_pb2 as blogkeeper__pb2


class BlogKeeperStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetInfo = channel.unary_unary(
        '/blogkeeper.BlogKeeper/GetInfo',
        request_serializer=blogkeeper__pb2.Blog.SerializeToString,
        response_deserializer=blogkeeper__pb2.BlogSummary.FromString,
        )
    self.ListArticles = channel.unary_stream(
        '/blogkeeper.BlogKeeper/ListArticles',
        request_serializer=blogkeeper__pb2.Blog.SerializeToString,
        response_deserializer=blogkeeper__pb2.Article.FromString,
        )


class BlogKeeperServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListArticles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlogKeeperServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetInfo,
          request_deserializer=blogkeeper__pb2.Blog.FromString,
          response_serializer=blogkeeper__pb2.BlogSummary.SerializeToString,
      ),
      'ListArticles': grpc.unary_stream_rpc_method_handler(
          servicer.ListArticles,
          request_deserializer=blogkeeper__pb2.Blog.FromString,
          response_serializer=blogkeeper__pb2.Article.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'blogkeeper.BlogKeeper', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
